apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  labels:
    {{- include "cert-manager-issuers.metadataLabels" $ | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email | quote }}
    privateKeySecretRef:
      name: letsencrypt-production-issuer-account-key
    solvers:
      - http01:
          ingress:
            {{- toYaml .Values.ingress | nindent 12 }}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    {{- include "cert-manager-issuers.metadataLabels" $ | nindent 4 }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.email | quote }}
    privateKeySecretRef:
      name: letsencrypt-staging-issuer-account-key
    solvers:
      - http01:
          ingress:
            {{- toYaml .Values.ingress | nindent 12 }}
